services:
  - type: web
    name: afcybersolutions-web
    env: python
    plan: free
    buildCommand: pip install -r requisitos.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: afcyber2026seguridadempresa
